# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create jar file

on:
  push:
    branches: [ "master" ]

jobs:
  DO-stuff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 2 - Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir my_package && cp target/*.jar me_package
    
    - name: Step 3 - Setup a cache for Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Step 4 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: my_package
